services:
  frontend:
    container_name: ubcms-frontend
    build:
      context: ./frontend
    env_file: .env
    environment:
      - DIRECTUS_API_URL=http://directus:${DIRECTUS_PORT}
      - PORT=${FRONTEND_PORT}
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    command: npm run dev
    depends_on:
      - directus

  database:
    container_name: ubcms-postgres
    image: postgres:18.1
    volumes:
      - directus-data:/var/lib/postgresql
      - ./backend/database/ubcms.sql:/docker-entrypoint-initdb.d/ubcms.sql
    env_file:
      - .env
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
    healthcheck:
      test: ['CMD', 'pg_isready', '--host=localhost', '--username=directus']
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    container_name: ubcms-redis
    image: redis:8.4.0
    healthcheck:
      test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    container_name: ubcms-directus
    image: directus/directus:11.15.1
    ports:
      - '${DIRECTUS_PORT}:${DIRECTUS_PORT}'
    volumes:
      - ./backend/uploads:/directus/uploads
      - ./backend/extensions:/directus/extensions
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - .env

volumes:
  directus-data:
    name: ubcms-directus-data
